#! /usr/bin/env python
# -*- coding: utf-8 -*-
import time
import pyowm
import telebot
from pyowm.exceptions.api_response_error import NotFoundError
from forex_python.converter import CurrencyRates, get_rates, RatesNotAvailableError

token = '811144163:AAF74Jn7ztetg6g9SY2SlQ-hG8PXxgIK5uE'


bot = telebot.TeleBot("811144163:AAF74Jn7ztetg6g9SY2SlQ-hG8PXxgIK5uE")

list = []


@bot.message_handler(content_types=['text'])
def proverka(message):
    if message.text == "Hello":
        weather1(message)
    elif message.text == "rat":
        qaz(message)
    elif message.text == "kypc":
        wtfisup(message)
    else:
        bot.send_message(message.chat.id, "напиши привет")

def weather1(message):
    city = bot.send_message(message.chat.id, "Where to show")
    bot.register_next_step_handler(city, wtf)



def wtf(message):
    owm = pyowm.OWM('9a5624fb9a6d6535203e750abacf0e32')
    cisy = message.text
    try:
        owm.weather_at_place(cisy)
    except NotFoundError:
        bot.send_message(message.chat.id, "Wrong information, try again to find out mistakes please")
        weather1(message)
    else:
        weather = owm.weather_at_place(cisy)
        w = weather.get_weather()
        temperature = w.get_temperature("celsius")["temp"]
        bot.send_message(message.chat.id, "weather" + "in" + str(cisy) + str(temperature))





def qaz(message):
    vopros = bot.send_message(message.chat.id, "Сколько")
    bot.register_next_step_handler(vopros, qwe)
def qwe(message):
    try:
        float(message.text)
    except ValueError:
        bot.send_message(message.chat.id, "введите число")
        qaz(message)
    else:
        quantity = list.append(message.text)
        vopros1 = bot.send_message(message.chat.id, "из чего")
        bot.register_next_step_handler(vopros1, qwer )

def qwer(message):
    try:
        get_rates(str(message.text.upper()))
    except RatesNotAvailableError:
        bot.send_message(message.chat.id, "вы неправильно ввели название валюты")
        vopros1 = bot.send_message(message.chat.id, "из чего")
        bot.register_next_step_handler(vopros1, qwer)
    else:
        izchego = list.append(message.text.upper())
        vopros2 = bot.send_message(message.chat.id, "Во что")
        bot.register_next_step_handler(vopros2, qwert)
def qwert(message):
    try:
        get_rates(str(message.text.upper()))
    except RatesNotAvailableError:
        bot.send_message(message.chat.id, "вы неправильно ввели название валюты")
        vopros2 = bot.send_message(message.chat.id, "Во что")
        bot.register_next_step_handler(vopros2, qwert)
    else:
        vochto = list.append(message.text.upper())
        c = CurrencyRates()
        q = c.convert(str(list[1]), str(list[2]), float(list[0]))
        bot.send_message(message.chat.id, q)
        refresh(message)
def refresh(message):
    list[:] = []

def wtfisup(message):
    c = CurrencyRates()
    list1 = ['USD', "EUR", "GBP"]
    for i in list1:
        q = c.convert(str(i), "RUB", 1)
        bot.send_message(message.chat.id,str(1)+ ' ' + str(i) + " " + '=' + " " + str(q) + " " + "RUB")

while True:

    try:

        bot.polling(none_stop=True)

    # ConnectionError and ReadTimeout because of possible timout of the requests library

    # TypeError for moviepy errors

    # maybe there are others, therefore Exception

    except Exception as e:

        telebot.logger.error(e)

        time.sleep(5)
