#! /usr/bin/env python
# -*- coding: utf-8 -*-
import time

import pyowm
import telebot
from pyowm.exceptions import api_response_error
token = '871805585:AAEgAuDU30QiwsAK0B0Aa0KSPdN8AylAsUY'


bot = telebot.TeleBot("871805585:AAEgAuDU30QiwsAK0B0Aa0KSPdN8AylAsUY")

list = []


@bot.message_handler(content_types=['text'])
def proverka(message):
    if message.text == "Hello":
        weather(message)
    elif message.text == "rat":
        qaz(message)
    else:
        bot.send_message(message.chat.id, "напиши привет")

def weather(message):
    city = bot.send_message(message.chat.id, "Where to show")
    bot.register_next_step_handler(city, wtf)



def wtf(message):
    owm = pyowm.OWM('9a5624fb9a6d6535203e750abacf0e32')
    cisy = message.text
    try:
        owm.weather_at_place(cisy)
    except:
        api_response_error.NotFoundError('Unable to find the resource')
        bot.send_message(message.chat.id, "Wrong information, try again to find out mistakes please")



    weather = owm.weather_at_place(cisy)

    w = weather.get_weather()
    temperature = w.get_temperature("celsius")["temp"]

    bot.send_message(message.chat.id, "weather" +  "in" + str(cisy) + str(temperature))







from forex_python.converter import CurrencyRates
def qaz(message):
    vopros = bot.send_message(message.chat.id, "Сколько")
    bot.register_next_step_handler(vopros, qwe)
def qwe(message):
    quantity = list.append(message.text)
    try:
        float(list[0])
    except:
        ValueError
        bot.send_message(message.chat.id, "введите число")
        qaz(message)
    if ValueError == False:
        vopros1 = bot.send_message(message.chat.id, "из чего")
        bot.register_next_step_handler(vopros1, qwer)

def qwer(message):
    izchego = list.append(message.text)
    vopros2 = bot.send_message(message.chat.id, "Во что")
    bot.register_next_step_handler(vopros2, qwert)
def qwert(message):
    vochto = list.append(message.text)

    c = CurrencyRates()

    q = c.convert(str(list[1]), str(list[2]), float(list[0]))
    bot.send_message(message.chat.id, q)
    refresh(message)
def refresh(message):
    list[:] = []


bot.polling()
