#! /usr/bin/env python
# -*- coding: utf-8 -*-

import time
import telebot
import pyowm

from telebot import types
from pyowm.exceptions.api_response_error import NotFoundError
from forex_python.converter import CurrencyRates, get_rates, RatesNotAvailableError

token = '811144163:AAF74Jn7ztetg6g9SY2SlQ-hG8PXxgIK5uE'


bot = telebot.TeleBot("811144163:AAF74Jn7ztetg6g9SY2SlQ-hG8PXxgIK5uE")

list = []


@bot.message_handler(content_types=['text'])
def greeting(message):
    if message.text == "Привет":
        soobshenie1 = bot.send_message(message.chat.id, '''1) Хочешь узнать погоду?
2) Хочешь сконвертировать валюты?
3) Хочешь узнать курс основных валют?''');
        vibor(message)
    else:
        soobshenie3 = bot.send_message(message.chat.id, "Поприветствуй меня!")

def vibor(message):
    punkt = bot.send_message(message.chat.id, "Выберите нужный пункт.")
    bot.register_next_step_handler(punkt, chooseone)
    
def chooseone(message):
    if message.text == "1":
        weather1(message)
    elif message.text == "2":
        qaz(message)
    elif message.text == "3":
        wtfisup(message)
    else:
        soobshenie2 = bot.send_message(message.chat.id, "Выберите нужный пункт.")




def weather1(message):
    city = bot.send_message(message.chat.id, "Погоду в каком городе хотите узнать?")
    bot.register_next_step_handler(city, wtf)



def wtf(message):
    owm = pyowm.OWM('9a5624fb9a6d6535203e750abacf0e32')
    cisy = message.text
    try:
        owm.weather_at_place(cisy)
    except NotFoundError:
        bot.send_message(message.chat.id, "Неправильно введен город, повторите ввод.")
        weather1(message)
    else:
        weather = owm.weather_at_place(cisy)
        w = weather.get_weather()
        temperature = w.get_temperature("celsius")["temp"]
        wind = w.get_wind()["speed"]
        hum = w.get_humidity()
        bot.send_message(message.chat.id, "Сейчас в городе " + str(cisy) + " " + "температура - " + str(temperature) + "°C, влажность - " + str(hum) + "%, скорость ветра - " +str(wind) + "м/с.")
        offkomanda(message)

def offkomanda(message):
    sprashivaet = bot.send_message(message.chat.id, "Могу быть еще чем-то полезен?")
    bot.register_next_step_handler(sprashivaet, question_1)


def question_1(message):
    if message.text == "Да":
        soobshenie1 = bot.send_message(message.chat.id, '''1) Хочешь узнать погоду?
2) Хочешь сконвертировать валюты?
3) Хочешь узнать курс основных валют?''');
        vibor(message)
    else:
        proshanie = bot.send_message(message.chat.id, "bye")





def qaz(message):
    vopros = bot.send_message(message.chat.id, "Сколько")
    bot.register_next_step_handler(vopros, qwe)
def qwe(message):
    try:
        float(message.text)
    except ValueError:
        bot.send_message(message.chat.id, "Введите число.")
        qaz(message)
    else:
        quantity = list.append(message.text)
        vopros1 = bot.send_message(message.chat.id, "Из чего?")
        bot.register_next_step_handler(vopros1, qwer )

def qwer(message):
    try:
        get_rates(str(message.text.upper()))
    except RatesNotAvailableError:
        bot.send_message(message.chat.id, "Вы неправильно ввели название валюты.")
        vopros1 = bot.send_message(message.chat.id, "из чего")
        bot.register_next_step_handler(vopros1, qwer)
    else:
        izchego = list.append(message.text.upper())
        vopros2 = bot.send_message(message.chat.id, "Во что?")
        bot.register_next_step_handler(vopros2, qwert)
def qwert(message):
    try:
        get_rates(str(message.text.upper()))
    except RatesNotAvailableError:
        bot.send_message(message.chat.id, "Вы неправильно ввели название валюты.")
        vopros2 = bot.send_message(message.chat.id, "Во что?")
        bot.register_next_step_handler(vopros2, qwert)
    else:
        vochto = list.append(message.text.upper())
        c = CurrencyRates()
        q = c.convert(str(list[1]), str(list[2]), float(list[0]))
        bot.send_message(message.chat.id, q)
        refresh(message)
    offkomanda(message)
def refresh(message):
    list[:] = []

def offkomanda(message):
    sprashivaet = bot.send_message(message.chat.id, "Могу быть еще чем-то полезен?")
    bot.register_next_step_handler(sprashivaet, question_1)


def question_1(message):
    if message.text == "Да":
        soobshenie1 = bot.send_message(message.chat.id, '''1) Хочешь узнать погоду?
2) Хочешь сконвертировать валюты?
3) Хочешь узнать курс основных валют?''');
        vibor(message)
    else:
        proshanie = bot.send_message(message.chat.id, "bye")

def wtfisup(message):
    c = CurrencyRates()
    list1 = ['USD', "EUR", "GBP", "JPY", "CNY"]
    for i in list1:
        q = c.convert(str(i), "RUB", 1)
        bot.send_message(message.chat.id,str(1) + " " + str(i) + " " + '=' + " " + str(round(float(q), 4)) + " " + \
                         "RUB")
    offkomanda(message)


def offkomanda(message):
    sprashivaet = bot.send_message(message.chat.id, "Могу быть еще чем-то полезен?")
    bot.register_next_step_handler(sprashivaet, question_1)


def question_1(message):
    if message.text == "Да":
        soobshenie1 = bot.send_message(message.chat.id, '''1) Хочешь узнать погоду?
2) Хочешь сконвертировать валюты?
3) Хочешь узнать курс основных валют?''');
        vibor(message)
    else:
        proshanie = bot.send_message(message.chat.id, "bye")

while True:

    try:

        bot.polling(none_stop=True)

    # ConnectionError and ReadTimeout because of possible timout of the requests library

    # TypeError for moviepy errors

    # maybe there are others, therefore Exception

    except Exception as e:

        telebot.logger.error(e)

        time.sleep(5)
